#!/usr/bin/env python3
"""
Stage 2: 代码修复

输入: CI 分析报告 + 源代码仓库（已 checkout 到 fix 分支）
输出: 源代码修改（git commit）+ 修复摘要文件
副作用: 评论 PR
"""

import os
import sys
import subprocess
from pathlib import Path

PROJECT_ROOT = str(Path(__file__).resolve().parent.parent.parent)
sys.path.insert(0, PROJECT_ROOT)

from scripts.lib.ai_runner import run_agent
from scripts.lib.stage_common import agent_prompt_file, log_stage, get_conventions_file
from scripts.lib.ci_github_api import add_pr_comment

WORK_BASE = os.path.join(Path.home(), 'tech-design-data', 'ci-fix')
SOURCE_REPO_DIR = os.path.join(PROJECT_ROOT, 'source-repo')


def parse_env() -> dict:
    source_repo = os.getenv('SOURCE_REPO', '')
    pr_number = int(os.getenv('PR_NUMBER', '0'))
    if not source_repo or not pr_number:
        raise ValueError('SOURCE_REPO and PR_NUMBER are required')
    owner, repo = source_repo.split('/', 1)
    return {
        'source_repo': source_repo,
        'owner': owner,
        'repo': repo,
        'pr_number': pr_number,
        'pr_title': os.getenv('PR_TITLE', ''),
        'pr_head_sha': os.getenv('PR_HEAD_SHA', ''),
        'fix_branch': os.getenv('FIX_BRANCH', f'fix/{pr_number}'),
        'pr_base_branch': os.getenv('PR_BASE_BRANCH', 'main'),
        'analysis': os.getenv('ANALYSIS', ''),
        'token': os.getenv('GITHUB_TOKEN', ''),
    }


def git(args: list, cwd: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(['git'] + args, cwd=cwd, check=check,
                          capture_output=True, text=True)


def has_changes(cwd: str) -> bool:
    result = git(['diff', '--cached', '--quiet'], cwd=cwd, check=False)
    return result.returncode != 0


def main():
    env = parse_env()
    work_dir = os.path.join(WORK_BASE, str(env['pr_number']))
    Path(work_dir).mkdir(parents=True, exist_ok=True)
    # 摘要文件写在 work_dir（源码库之外），不会被 git commit 进去
    output_file = os.path.join(work_dir, 'code-fix-summary.md')

    log_stage('code-fix', f"repo={env['source_repo']} pr=#{env['pr_number']}")

    if not env['analysis']:
        raise RuntimeError('ANALYSIS env var is empty — ci-log-analysis must run first')

    if not os.path.isdir(SOURCE_REPO_DIR):
        raise RuntimeError(f'source-repo directory not found: {SOURCE_REPO_DIR}')

    context = {
        'pr': {
            'number': env['pr_number'],
            'title': env['pr_title'],
        },
        'ci_analysis': env['analysis'],
        'fix_branch': env['fix_branch'],
    }

    # AI Agent 在源码仓库目录中运行，直接读写源文件
    run_agent(
        prompt_file=agent_prompt_file('code-fixer'),
        context=context,
        instruction=(
            '根据 CI 失败分析报告，对源代码进行最小化修复。'
            '修复完成后，将修复摘要写入 output_file（不要写入源码仓库内部）。'
        ),
        work_dir=SOURCE_REPO_DIR,
        output_file=output_file,
        label='code-fix',
        conventions_file=get_conventions_file(),
    )

    # git add + commit（push 由 workflow 负责）
    log_stage('code-fix', 'staging changes...')
    git(['add', '-A'], cwd=SOURCE_REPO_DIR)

    if not has_changes(SOURCE_REPO_DIR):
        raise RuntimeError('code-fixer made no changes — cannot commit empty diff')

    with open(output_file, 'r', encoding='utf-8') as f:
        summary = f.read().strip()

    first_line = summary.split('\n')[0].lstrip('#').strip()[:72]
    commit_msg = (
        f"fix(ci): {first_line}\n\n"
        f"Automated fix for CI failure in PR #{env['pr_number']}\n\n"
        f"🤖 Generated by ci-fix-team"
    )

    git(['commit', '-m', commit_msg], cwd=SOURCE_REPO_DIR)
    log_stage('code-fix', '✅ committed')

    # 评论到原始 PR
    comment_body = (
        f"## 🔧 代码修复完成 (code-fix)\n\n"
        f"**PR**: #{env['pr_number']} — {env['pr_title']}\n"
        f"**Fix branch**: `{env['fix_branch']}`\n\n---\n\n"
        f"{summary}"
    )
    try:
        add_pr_comment(env['source_repo'], env['pr_number'], comment_body, env['token'])
    except Exception as e:
        log_stage('code-fix', f'⚠️ PR comment failed: {e}')

    log_stage('code-fix', '✅ done')


if __name__ == '__main__':
    main()
