#!/usr/bin/env python3
"""
生成 Fix PR 的标题和正文，供 workflow 的 Create fix PR 步骤调用。

从 ci-data 分支读取分析报告和修复摘要，输出 JSON：
  {"title": "...", "body": "..."}
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
from scripts.lib import ci_data


def extract_section(text: str, heading: str) -> str:
    lines, capturing, result = text.splitlines(), False, []
    for line in lines:
        if re.match(r'#+\s*' + re.escape(heading), line):
            capturing = True
            continue
        if capturing:
            if line.startswith('#'):
                break
            result.append(line)
    return '\n'.join(result).strip()


def extract_field(text: str, field: str) -> str:
    for line in text.splitlines():
        if field in line and ':' in line:
            v = line.split(':', 1)[-1].strip().lstrip('*').strip()
            if v:
                return v
    return ''


def build(pr_num: int, pr_title: str) -> dict:
    analysis    = ci_data.read_file(ci_data.analysis_path(pr_num)) or ''
    fix_summary = ci_data.read_file(ci_data.fix_summary_path(pr_num)) or ''

    root_cause = extract_section(analysis, '根因定位') or extract_section(analysis, '直接错误')
    fix_desc   = extract_section(fix_summary, '修复逻辑') or extract_section(fix_summary, '修复的问题')
    fix_files  = extract_section(fix_summary, '修改的文件')
    fail_type  = extract_field(analysis, '失败类型')

    m = re.search(r'】(.+?)(?:容器镜像)?升级至([\d][\w.\-]+?)(?=版本|$|\s)', pr_title)
    if m:
        title = f"fix: {m.group(1).strip()} {m.group(2).strip()} (fix #{pr_num})"
    else:
        title = f"fix: {pr_title} (fix #{pr_num})"
    body  = f"""## Fix for #{pr_num}

**Root cause**:
{root_cause or '(see CI analysis)'}

**Fix**:
{fix_desc or '(see fix summary)'}

**Modified files**:
{fix_files or '(see commit diff)'}

---
- Failure type: `{fail_type or 'unknown'}`
- Original PR: #{pr_num} — {pr_title}
- 🤖 Generated by ci-fix-team"""

    return {'title': title, 'body': body}


if __name__ == '__main__':
    pr_num   = int(os.environ['PR_NUMBER'])
    pr_title = os.environ['PR_TITLE']
    print(json.dumps(build(pr_num, pr_title), ensure_ascii=False))
